/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package demo

import groovy.transform.CompileStatic

@CompileStatic
class App {
    static getDay1() {
        File file = new File("input.txt")

        def list = [] as ArrayList<Integer>
        def count = 0
        def largest = 0
        file.eachLine { line ->
            if (line == "") {
                count++
            } else {
                if (list[count] == null) {
                    list << line.toInteger()
                } else {
                    list[count] = list[count] + line.toInteger()
                }
                if (list[count] > largest) {
                    largest = list[count]
                }
            }
        }

        if (System.getenv("part") == "part1") {
            return largest
        }
        if (System.getenv("part") == "part2") {
            list.sort()
            def top3 = list[-3] + list[-2] + list[-1]
            return top3
        }
    }

    static void main(String[] args) {
        println day1
    }
}


