/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package demo

import org.apache.commons.io.FileUtils;

import groovy.transform.CompileStatic

import java.nio.file.Files
import java.nio.file.Path

@CompileStatic
class App {

    static day7BuildDirs() {
        new File(baseDir).deleteDir()

        new File(baseDir).mkdir()
        Files.lines(Path.of("input7.txt"))
                .skip(1)
                .forEach { line ->
                    {
                        findAndFireCommand(line)
                    }
                }
    }

    static void main(String[] args) {
        println "Groovy"
        if (System.getenv("part") == "part1") {
            day7BuildDirs()
            println part1()
        } else {
            day7BuildDirs()
            println part2()
        }
    }
    public static final String baseDir = String.format("%s%saoc", ".", File.separator)
    public static String currentDir = String.format("%s/aoc", ".")
    public static boolean writeMode = false

    static String part1() {
        def sum = 0
        Files.walk(Path.of(baseDir))
                .forEach { path ->
                    {
                        if (path.toFile().isDirectory()) {
                            def size = FileUtils.sizeOfDirectory(path.toFile())
                            if (size <= 100000) sum += size
                        }
                    }
                }
        return sum.toString()
    }

    static String part2() {

        int totalSpace = 70000000, needSpace = 30000000, smallestDir = Integer.MAX_VALUE, usedSpace = (int) FileUtils.sizeOfDirectory(new File(baseDir)), currentSpace = totalSpace - usedSpace
        Files.walk(Path.of(baseDir))
                .forEach { path ->
                    {
                        if (path.toFile().isDirectory()) {
                            int size = (int) FileUtils.sizeOfDirectory(path.toFile())
                            if (currentSpace + size >= needSpace && size < smallestDir) smallestDir = size
                        }
                    }
                }
        return smallestDir
    }

    static void findAndFireCommand(String s) {
        if (s.startsWith("\$ cd")) {
            if (s.contains("..")) {
                currentDir = currentDir.substring(0, currentDir.lastIndexOf("/"))
            } else {
                currentDir = String.format("%s/%s", currentDir, s.find(/[\w.]+(?=$)/))
            }
            writeMode = false
        } else if (s.contains("\$")) {
            writeMode = false
        }
        if (writeMode) {
            if (s.contains("dir")) {
                new File(String.format("%s/%s", currentDir, s.find(/\s+([\w]+)/).trim())).mkdir()
            } else {
                def fileSize = s.substring(0, s.lastIndexOf(" "))
                def file = new File(String.format("%s/%s", currentDir, fileSize))
                try(FileOutputStream fos = new FileOutputStream(file)){
                    byte[] arr = new byte[fileSize.toInteger()];
                    new Random().nextBytes(arr);
                    fos.write(arr)
                }
            }
        }
        if (s.contains("ls")) {
            writeMode = true // next line is a file or dir
        }
    }
}


