/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package demo

import spock.lang.Specification

class AppTest extends Specification {
    def "application can run"() {
        expect:
        true
    }
}
